apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gatekeeper-library-policies
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements: 
      - name: in-cluster
  template:
    metadata:
      name: gatekeeper-library-policies
    spec:
      project: rhacm-policies
      source:
        repoURL: https://github.com/kairen/rhacm-policygenerator-demo.git
        targetRevision: main
        path: gatekeeper-library
      destination:
        namespace: rhacm-policies
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        syncOptions:
          - SkipDryRunOnMissingResource=true
