apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rhacm-policies
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist: # TODO: PoLP
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
